apply patch from Bug 32501 - [QuestyCaptcha] Help page is broken
Fixes:

  When trying to open the help page, the following messages appear:
<pre>
Notice: Undefined property: QuestyCaptcha::$storage in
/.../extensions/ConfirmEdit/QuestyCaptcha.class.php on line 68

Fatal error: Call to a member function cookiesNeeded() on a non-object in
/.../extensions/ConfirmEdit/QuestyCaptcha.class.php on line 68
</pre>

Might need to be merged so Extension Distributor can use it?


git-svn-id: svn+ssh://svn.wikimedia.org/svnroot/mediawiki/trunk/extensions@104867 dd0e9695-b195-4be7-bd10-2dea1a65a6b6